services:
  redis:
    image: redis:7-alpine
    container_name: xyzyblog-redis
    restart: unless-stopped
    ports:
      - "6180:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - xyzyblog-redis-data:/data

volumes:
  xyzyblog-redis-data:
